config/routes.rb
Rails.application.routes.draw do
  root "chatroom#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :messages, only: [ :create ]


  mount ActionCable.server, at: "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages,  dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)

    if message.save
      ActionCable.server.broadcast "chatroom_channel",
                                   { mod_message: message_render(message) }
      redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render_to_string(partial: "messages/message", locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [ :new, :create ]
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully"
      redirect_to root_path   # or chatroom_path or wherever
    else
      flash.now[:error] = "There was something wrong with your login details"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private
  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="circular orange users icon"></i>
  Say something
</h2>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_with(scope: :message, url: messages_path, local: true, data: { turbo: false }, class: "ui reply form") do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: "Enter a message" %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col-10">
      <% flash.each do |name, msg| %>
        <div class="ui <%=name%> message">
          <i class="close icon"></i>
          <%= msg %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<%= link_to 'Chatroom', root_path, class: "item" %>

<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? && current_user %>
        <%= link_to 'Log out', logout_path, data: { turbo_method: :delete }, class: "item" %>
      <% else %>
        <%= link_to 'Log in', login_path, class: "item" %>
      <% end %>

    </div>
  </div>
  <% if !logged_in? %>
    <div class="item">
      <%= link_to 'Log in', login_path, class: "ui primary button" %>
    </div>

  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Message Me" %></title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "semantic", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="ui small menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>

      </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/messages/_message.html.erb
            
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>